# Generated by Django 5.2.4 on 2025-08-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactForm",
            new_name="ContactData",
        ),
    ]
