# Generated by Django 5.2.4 on 2025-08-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_contactform_contactdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactData",
        ),
    ]
