# Generated by Django 5.2.4 on 2025-08-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_producto",
                    models.CharField(max_length=100, verbose_name="Producto"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=0, max_digits=5, verbose_name="Precio"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stock")),
                (
                    "imagen",
                    models.ImageField(upload_to="productos/", verbose_name="Imagen"),
                ),
            ],
        ),
    ]
