# Generated by Django 5.2.4 on 2025-08-12 22:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flan",
            fields=[
                (
                    "flan_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, verbose_name="Nombre del flan"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de la imagen"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="¿Es privado?"),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=0, max_digits=5, verbose_name="Precio"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stock")),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="productos/",
                        verbose_name="Imagen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flan",
                "verbose_name_plural": "Flanes",
            },
        ),
        migrations.DeleteModel(
            name="Producto",
        ),
    ]
