# Generated by Django 5.2.4 on 2025-08-14 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_contactform"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_form_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("customer_email", models.EmailField(max_length=254)),
                (
                    "customer_name",
                    models.CharField(max_length=64, verbose_name="Nombre del cliente"),
                ),
                ("message", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="ContactForm",
        ),
    ]
