# Generated by Django 5.2.4 on 2025-08-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_contactdata_delete_contactform"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactdata",
            old_name="contact_form_uuid",
            new_name="contact_data_uuid",
        ),
    ]
