# Generated by Django 5.2.4 on 2025-08-21 15:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_rename_contact_form_uuid_contactdata_contact_data_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactdata",
            options={
                "verbose_name": "Dato de Contacto",
                "verbose_name_plural": "Datos de Contacto",
            },
        ),
        migrations.AddField(
            model_name="contactdata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactdata",
            name="contact_data_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
